spring:
  application:
    name: flightbooking
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/flight-booking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  web:
    resources:
      static-locations: "classpath:/public/"
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: ${PORT:8080}
