spring:
  application:
    name: flightbooking
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/flight-booking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
server:
  port: ${PORT:8080}
